default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: spa_example_development

test:
  <<: *default
  database: spa_example_test

production:
  <<: *default
  database: spa_example_production
  username: deployer
  password: <%= ENV['DATABASE_PASSWORD'] %>